sonar.host.url=https://sonarcloud.io
sonar.projectKey=hungles_devsecops-proyect
sonar.organization=hungles
sonar.sources=.
sonar.exclusions=tests/**
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true